engines:
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
    exclude_paths:
      - "**/*"
      - "!**/*.md"
ratings:
  paths:
  - "downgrade"
exclude_paths:
  - "completion/*"
  - "test/*"
