#!/usr/bin/env bash
# shellcheck disable=SC1091
. gettext.sh
export TEXTDOMAIN=downgrade
export TEXTDOMAINDIR=/usr/share/locale

read_pacman_conf() { sed '/^#\?'"$1"' *= *\(.*\)$/!d; s//\1/' "$PACMAN_CONF"; }

previously_installed() {
  # Delay this defaulting so #read_pacman_conf behavior is tested
  : "${PACMAN_LOG:=$(read_pacman_conf LogFile)}"
  : "${PACMAN_LOG:=/var/log/pacman.log}"

  sed '
    /.*\(installed\|upgraded\) \('"$1"'\) (\(.* -> \)\?\([^)]*\))/!d
    s//\2-\4/
  ' "$PACMAN_LOG"
}

currently_installed() {
  LC_ALL=C.UTF8 "$PACMAN" -Qi "$1" 2>/dev/null | awk -F " : " '
    /^Name / { name=$2 };
    /^Version / { version=$2 };
    END { if (name != "") printf("%s-%s\n", name, version) }
  '
}

# <package name> [package path] …
present_packages() {
  local i=1
  local pkgname="$1"
  shift

  (($#)) || return 1

  gettext 'Available packages:'
  printf '\n\n'

  for entry; do
    output_package "$((i++))" "$entry" "$pkgname"
  done | column -s '	' -t -R 2,4,6
  # Expand tabs in the output of output_package to spaces as needed to create a
  # table. Right align numerical columns 2 (index), 4 (epoch) and 6 (release).

  printf '\n'
  gettext 'select a package by number: '
}

read_selection() {
  local ans

  read -r ans

  if [ "$ans" == "q" ]; then
      printf "%s" "$ans"
  else
      ((ans > 0 && ans <= $#)) && printf "%s" "${!ans}"
  fi
}

enumerate_array() {
    local i=1
    local array=("$@")
    for entry in "${array[@]}"; do
        printf "%s)\t%s\n" "$((i++))" "$entry"
    done
    printf "q)\texit\n"
}

prompt_to_ignore() {
  local pkg ans ln

  for pkg; do
    grep -Eq '^IgnorePkg.*( |=)'"$pkg"'( |$)' "$PACMAN_CONF" && return 0

    eval_gettext "add \$pkg to IgnorePkg? [y/n] "
    read -r ans

    if [[ "${ans,,}" == $(gettext 'y')* ]]; then
      ln="$(grep -n -m 1 '^ *IgnorePkg' "$PACMAN_CONF" | cut -d : -f 1)"
      if [ -n "$ln" ]; then
        sudo sed -i "$ln s/.*/& $pkg/" "$PACMAN_CONF"
        continue
      fi

      ln="$(grep -n '^# *IgnorePkg' "$PACMAN_CONF" | tail -n 1 | cut -d : -f 1)"
      if [ -n "$ln" ]; then
        sudo sed -i "$ln s/.*/&\\nIgnorePkg = $pkg/" "$PACMAN_CONF"
        continue
      fi

      printf "IgnorePkg = %s\\n" "$pkg" | sudo tee -a "$PACMAN_CONF"
    fi
  done
}

downgrade_dependencies() {
    # create localized variables
    local pkg tree delete dep_array ans target i
    for pkg; do
        # assign initial variables
        tree=$(pactree -r "$pkg")
        delete=("$pkg")
        dep_array=($(pactree -r -u -l "$pkg"))
        # clear pactree reverse graph of original function
        for target in "${delete[@]}"; do
            for i in "${!dep_array[@]}"; do
                if [[ ${dep_array[i]} == "$target" ]]; then
                    unset 'dep_array[i]'
                fi
            done
        done
        # check if there are dependencies at all
        if [ ${#dep_array[@]} -eq 0 ]; then
            return 0
        # if dependencies are detected, enter loop
        else
            # while loop to downgrade dependencies
            eval_gettext "review and downgrade depedencies of \$pkg? [y/n] "
            read -r ans
            if [[ "${ans,,}" == $(gettext 'y')* ]]; then
                while true
                do
                    printf 'Dependency graph:\n\n'
                    printf "%s" "$tree"
                    printf '\n\n'
                    gettext 'Dependencies to downgrade:'
                    printf '\n'
                    enumerate_array "${dep_array[@]}"
                    printf '\n'
                    gettext 'select a package by number: '
                    choice=$(read_selection "${dep_array[@]}")
                    if [ "$choice" == "q" ]; then
                        break
                    else
                        unset to_install
                        unset to_ignore
                        main "$choice"
                        sudo pacman -U "${pacman_args[@]}" "${to_install[@]}"
                        prompt_to_ignore "${to_ignore[@]}"
                    fi
                done
            fi
        fi
    done
}

search_packages() {
  local name version index

  if [[ "$1" =~ -([0-9R].*)$ ]]; then
    version=${BASH_REMATCH[1]}
    name=${1%-$version}
  else
    version='[0-9R]'
    name=$1
  fi

  index="$DOWNGRADE_ALA_URL/packages/${name:0:1}/$name/"

  if ((DOWNGRADE_FROM_ALA)); then
    curl --fail --silent "$index" | sed '
      /.* href="\('"$name-$version"'.*\(any\|'"$DOWNGRADE_ARCH"'\)\.pkg\.tar\.xz\)".*/!d;
      s||'"$index"'\1|g; s|+| |g; s|%|\\x|' | xargs -0 printf "%b"
  fi

  if ((DOWNGRADE_FROM_CACHE)); then
    # Delay this defaulting so #read_pacman_conf behavior is tested
    : "${PACMAN_CACHE:=$(read_pacman_conf CacheDir)}"
    : "${PACMAN_CACHE:=/var/cache/pacman/pkg/}"

    # shellcheck disable=SC2086
    find $PACMAN_CACHE -maxdepth 1 -name "$name-$version*.pkg.tar.[gx]z"
  fi
}

sort_packages() {
  grep -Fv 'testing/' |
    awk 'BEGIN { FS="/"; OFS="|" } { print $NF, $0 }' |
    pacsort -f -t '|' -k 1 | cut -d '|' -f 2-
}

# <number> <path> <package name>
output_package() {
  local number="$1" path="$2" pkgname="$3"
  local pkg indicator=" " location version epoch arch release

  if [[ -n "$current" ]] && [[ "$path" == *"$current"* ]]; then
    # Currently installed
    indicator="+"
  else
    for pkg in "${installed[@]}"; do
      case "$path" in
        *$pkg*)
          indicator="-"
          break
          ;;
      esac
    done
  fi

  # Remote or local file
  if [[ $path =~ ^/ ]]; then
    location="$(gettext 'local')"
  else
    location="$(gettext 'remote')"
  fi

  IFS=, read -r epoch version release arch < <(
    extract_version_parts "$pkgname" "$path"
  )

  printf "%s\t%s)\t%s\t%s\t%s\t%s\t%s\t(%s)\n" \
    "$indicator" \
    "$number" \
    "$pkgname" \
    "$epoch" \
    "$version" \
    "$release" \
    "$arch" \
    "$location"
}

# <package name> <package path>
extract_version_parts() {
  local pkgname=$1 path=$2 location version epoch arch release

  sed '
    # Strip first path component
    s|^.*/||;

    # Strip package name
    s|^.\{'${#pkgname}'\}-\?||;

    # Strip package extension
    s|\.pkg\(\.tar\)\?\(\.[a-z0-9A-Z]\+\)\?$||;

    # (epoch:)?version(-release)?(-arch)? -> epoch,version,release,arch
    s|\(\([^:]*\):\)\?\([^-]*\)\(-\([^-]*\)\)\?\(-\(.*\)\)\?|\2,\3,\5,\7|;
  ' <<<"$path"
}

# shellcheck disable=SC2207
process_term() {
  local term=$1 candidates choice

  candidates=($(search_packages "$term" | sort_packages))

  if (("${#candidates[@]}" == 1)); then
    choice=${candidates[0]}
  else
    if present_packages "$term" "${candidates[@]}"; then
      choice=$(read_selection "${candidates[@]}")
    fi
  fi

  if [[ -n "$choice" ]]; then
    to_ignore+=("$term")
    to_install+=("$choice")
    return 0
  fi

  return 1
}

main() {
  local term candidates choice pkg exit_code=0

  (($#)) || return 1

  for term; do
    # shellcheck disable=SC2207
    installed=($(previously_installed "$term"))
    current=$(currently_installed "$term")
    process_term "$term" || exit_code=1
  done

  return $exit_code
}

# Up-convert older variables
: "${DOWNGRADE_ARCH:=$ARCH}"
: "${DOWNGRADE_ALA_URL:=$ALA_URL}"
: "${DOWNGRADE_ALA_URL:=$ARM_URL}"
: "${DOWNGRADE_NOSUDO:=$NOSUDO}"

[ "$NOALA" = "1" ] && DOWNGRADE_FROM_ALA=0
[ "$NOARM" = "1" ] && DOWNGRADE_FROM_ALA=0
[ "$NOCACHE" = "1" ] && DOWNGRADE_FROM_CACHE=0

# Set script defaults
: "${PACMAN:=pacman}"
: "${PACMAN_CONF:=/etc/pacman.conf}"
: "${DOWNGRADE_ARCH:=$(uname -m)}"
: "${DOWNGRADE_ALA_URL:=https://archive.archlinux.org}"
: "${DOWNGRADE_FROM_ALA:=1}"
: "${DOWNGRADE_FROM_CACHE:=1}"
: "${DOWNGRADE_NOSUDO:=0}"

declare -a terms
declare -a to_ignore
declare -a to_install
declare -a pacman_args
declare -a installed

cli() {
  while [[ -n "$1" ]]; do
    case "$1" in
      --)
        shift
        pacman_args=("$@")
        break
        ;;
      *)
        terms+=("$1")
        shift
        ;;
    esac
  done

  if ((!"${#terms[@]}")); then
    (
      gettext 'usage: downgrade <pkg> [pkg...] [-- pacman_option...]'
      echo
      gettext 'see downgrade(8) for details.'
      echo
    ) >&2
    exit 1
  fi

  if ((DOWNGRADE_NOSUDO)) || ! type -p sudo &>/dev/null; then
    sudo() {
      printf -v cmd "%q " "$@"
      su root -c "$cmd"
    }
  fi

  main "${terms[@]}"
  sudo pacman -U "${pacman_args[@]}" "${to_install[@]}"
  prompt_to_ignore "${to_ignore[@]}"
  downgrade_dependencies "${terms[@]}"
}

if ((!LIB)); then
  set -e
  cli "$@"
fi
