.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "PACIGNORE" "8" "April 2025" ""
.SH "NAME"
\fBpacignore\fR \- ignore arch linux packages
.SH "SYNOPSIS"
\fBpacignore\fR ls \fIOPTIONS\fR
.br
\fBpacignore\fR \fIcheck|add|rm\fR \fIOPTIONS\fR \fIPKG\fR [PKG\|\.\|\.\|\.]
.SH "DESCRIPTION"
Ignore Arch Linux packages\.
.SH "SUBCOMMANDS"
.TP
\fBls\fR \fIPKG\fR [PKG\|\.\|\.\|\.]
List package(s) in the \fBIgnorePkg\fR directive\.
.TP
\fBcheck\fR \fIPKG\fR [PKG\|\.\|\.\|\.]
Check if package(s) are included in the \fBIgnorePkg\fR directive\.
.TP
\fBadd\fR \fIPKG\fR [PKG\|\.\|\.\|\.]
Add package(s) to the \fBIgnorePkg\fR directive\.
.TP
\fBrm\fR \fIPKG\fR [PKG\|\.\|\.\|\.]
Remove package(s) from the \fBIgnorePkg\fR directive\.
.SH "OPTIONS"
.TP
\fB\-c\fR \fIPATH\fR
Pacman configuration file, default is \fI/etc/pacman\.conf\fR\.
.TP
\fB\-h\fR
Show help script\.
.SH "EXIT CODES"
\fBpacignore\fR will return non\-zero if it encounters any of the following scenarios:
.IP "\(bu" 4
No argument value(s) supplied where necessary
.IP "\(bu" 4
No package(s) supplied for \fBcheck\fR, \fBadd\fR or \fBrm\fR subcommands
.IP "\(bu" 4
Execution from non\-root user for \fBadd\fR and \fBrm\fR subcommands
.IP "\(bu" 4
If any packages supplied to \fBcheck\fR subcommand are not included in the \fBIgnorePkg\fR directive
.IP "\(bu" 4
If any packages supplied to \fBrm\fR subcommand are not included in the \fBIgnorePkg\fR directive
.IP "\(bu" 4
If any packages supplied to \fBadd\fR subcommand are already included in the \fBIgnorePkg\fR directive
.IP "" 0
.SH "SEE ALSO"
\fBsudo(8)\fR, \fBpacman\.conf(5)\fR, \fBsu(1)\fR\.
.SH "BUGS"
Open a GitHub issue on \fIhttps://github\.com/archlinux\-downgrade/downgrade\fR\.
.SH "AUTHORS"
.IP "\(bu" 4
Patrick Brisbin <pbrisbin@gmail\.com>
.IP "\(bu" 4
Atreya Shankar <shankar\.atreya@gmail\.com>
.IP "" 0

