name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: "archlinux:base-devel"

    env:
      FIXTURES_NO_RECORD: 1

    steps:
      - uses: actions/checkout@v6
      - run: pacman -Sy --needed --noconfirm git just python-cram
      - run: just test
