name: Pages

on:
  push:
    branches: "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Install just as task-runner
        uses: extractions/setup-just@v3

      - name: Install mandoc for HTML conversion
        run: sudo apt-get install -y mandoc

      - name: Generate HTML man-pages
        run: just docs-html

      - name: Copy HTML sources to _site
        run: |
          mkdir -p _site
          cp -v doc/*.css doc/*.html _site/
          cp -v _site/downgrade.8.html _site/index.html

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v4
