name: Release

on:
  push:
    branches:
      - main
      - rc/*

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: "archlinux:base-devel"

    steps:
      - name: Setup packages
        run: sudo pacman -Sy --needed --noconfirm git nodejs npm

      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
            git+https://github.com/pbrisbin/semantic-release-aur.git#main
        env:
          FORCE_COLOR: 1

      # TEMPORARY
      - run: |
          ./bin/downgrade --version
          grep DOWNGRADE_VERSION bin/downgrade
